### ISSUE TITLE
Bug: Addition Error

### ISSUE THREAD

**Issue by yashhsm** [SuperteamDAO/superteam-reputation#7]
The category-wise reputation doesn’t add up to total reputation in some cases like “Yashhsm#9203”

**Comment by appsplash99** [comment]
Looking right into it right now...
@yashhsm can you please assign this to me ??

**Comment by appsplash99** [comment]
<img width="397" alt="Screenshot 2022-12-11 at 6 07 39 PM" src="https://user-images.githubusercontent.com/65857855/206904006-c409a835-8f85-4003-abb5-2f726d09cf1f.png">

_findings:_

The above screenshot is from the current response of the backend API from the .env.local file,
In our Frontend code on [line#64 in TableRow.tsx](https://github.com/SuperteamDAO/superteam-reputation/blob/prod/src/components/Dashboard/Row/TableRow.tsx#L64):

_we are consuming `total_amount` key which has value `1672` in backend;
where as the manual sum of XP amounts(`amount` keyName) of individual skill objects sums up to be:
20 + 200 + 1435 + 1267 -> `2922`._

`Possible Resolutions`:
1. Frontend Fix(_temporary_): instead of consuming the total_amount key we can manually show the total in frontend - _but i would really not recommend this, because if this is a backend issue this can happen often with multiple user accounts_
2. _Backend Fix:_ With the above findings -  _a permanent fix would be in the backend_ - the way we are capturing/calculating and storing the data in DB.
  If we also have a backend repo setup publically - i can check that as well.

**Comment by irffanasiff** [comment]
thanks @appsplash99 appreciate your work, we are directly fetching the total stored in the airtable for now we are not calculating it for now anywhere not in the fontend and backend. It needs to be fixed manually.

**Comment by appsplash99** [comment]
can you please assign it to me ??
@irffanasiff

**Comment by irffanasiff** [comment]
These issues can not be assigned it can only be solved by internal team. I will create more issues which you can take.
